### PR TITLE
add language selection

### LINKED ISSUE #127: Feature Request: Option to Manually select language
Some times the language detector of the application is not accurate, in my case i have to install english language tools among the spanish and that affect the language of the application (starts in english), i have to run videomass with

` LC_ALL=es videomass`

To get the spanish language in the application

### PR DESCRIPTION
**Pull request by jeanslack**
Closes #127 

@katnatek please check whether this solves your issue

The code in this PR allows you to select the application language. Please set it using the preferences dialog.
Also, the string on line 14 of the Spanish language `videomass.po` file has been changed from `es` to `es_ES`. Maybe that was what was causing the problem.

### CODE REVIEW

**Comment by katnatek** [comment]
Produce error when you try to open the Preference section,  if the variant of spanish is not es_ES like in my case that is es_MX
```
videomass 
Info: executable=/usr/bin/videomass
12:16:39: Debug: Adding duplicate image handler for 'Windows bitmap file'
12:16:39: Debug: Adding duplicate animation handler for '1' type
12:16:39: Debug: Adding duplicate animation handler for '2' type
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/videomass/vdms_main/main_frame.py", line 1289, in Setup
    with preferences.SetUp(self) as set_up:
  File "/usr/lib/python3.8/site-packages/videomass/vdms_dialogs/preferences.py", line 547, in __init__
    self.current_settings()  # call function for initialize setting layout
  File "/usr/lib/python3.8/site-packages/videomass/vdms_dialogs/preferences.py", line 556, in current_settings
    lang = SetUp.LOCALE_NAMES[self.appdata['locale_name']]
KeyError: 'es_MX'

```

**Comment by jeanslack** [comment]
Did the application start with the correct language before you opened the preferences?

**Comment by katnatek** [comment]
> Did the application start with the correct language before you opened the preferences?

Negative, still start in english

**Comment by katnatek** [comment]
Maybe you can get inspiration from how it handle yt-dlg https://github.com/oleksis/youtube-dl-gui/blob/master/youtube_dl_gui/app.py

**Comment by jeanslack** [comment]
> Maybe you can get inspiration from how it handle yt-dlg https://github.com/oleksis/youtube-dl-gui/blob/master/youtube_dl_gui/app.py

Yes, thank you, that's what I did. I removed the `wx.LANGUAGE_DEFAULT` value (gets the user's default/preferred language from the OS) which was causing the problem.
It should work now, can you try again please?

**Pull request merged**
