### PR TITLE
add queue management feature

### PR DESCRIPTION
**Pull request by jeanslack**
This PR adds the ability to manage queue files. Each item added to the queue will can have different settings, such as different times trimming and all the other nice things available on Videomass. This feature is only available for `A/V Conversions` and `Presets Manager`.

### CODE REVIEW

**Comment by johannesdedoper** [comment]
wow, sounds great, let me know if you need someone to test this?
cheers,
J.

**Comment by jeanslack** [comment]
Yes, now we need to do some testing. I've tested as much as I can but I may have forgotten something. Can you try the program in this PR yourself?

**Comment by johannesdedoper** [comment]
ok, I like to test it, can I use the master? or how can I test this?

**Comment by jeanslack** [comment]
Great! 
You need to download this branch not the master: https://github.com/jeanslack/Videomass/archive/refs/heads/queue-management.zip

Thank you very much.

**Comment by johannesdedoper** [comment]
Good evening,

So I did a first test using the [queue-management.zip](https://github.com/jeanslack/Videomass/archive/refs/heads/queue-management.zip). 
I just found a few small things:
1. At start complaining:

```
Info: frozen=False meipass=False launcher=True
19:23:19: Debug: Adding duplicate image handler for 'Windows bitmap file'
Traceback (most recent call last):
  File "/home/tr4/Downloads/Videomass-queue-management/videomass/gui_app.py", line 110, in OnInit
    main_frame = MainFrame()
  File "/home/tr4/Downloads/Videomass-queue-management/videomass/vdms_main/main_frame.py", line 186, in __init__
    self.videomass_tool_bar()
  File "/home/tr4/Downloads/Videomass-queue-management/videomass/vdms_main/main_frame.py", line 1314, in videomass_tool_bar
    pqueue = self.toolbar.AddTool(37, _('Process Queue'),
wx._core.wxAssertionError: C++ assertion "bitmap.IsOk()" failed at ../src/gtk/toolbar.cpp(262) in SetImage(): invalid bitmap for wxToolBar icon
OnInit returned false, exiting...
```

I just added the following png files to the Videomass-queue-management/videomass/art/icons/Videomass-Colours/24x24/ folder: 

- _proc-queue.png_
- _add-queue.png_

by converting the svg version.

Than it starts, just notifying:
```
Info: frozen=False meipass=False launcher=True
19:28:51: Debug: Adding duplicate image handler for 'Windows bitmap file'

```
2. The queue management 

- When adding to queue: it would be nice to see something of a counter when you add a profile to the queue.
- Remove (all) works fine
- Exporting the queue works but in Linux (PopOs) I have to manually add the extension. Otherwise you will not see the file when you want to import.
- Importing a queue can only be done when you already are in the Queue Processing menu, so you first have to add something to the queue before you can open/import your earlier exported queue.

3. Processing
Works fine, it only shows the status of the last profile that was queued.
Would be nice when it shows all encodings like usual.
Selection_004

Nice feature!
Probably impossible but just very nice would be parallel processing.
Well we keep that for another time. 
Do not get me wrong, this little program is my BPF (Best Program Forever) ;)
That's it for now.
Cheers, J

**Comment by jeanslack** [comment]
Good morning!
I just added a feature to ensure that data added to the queue does not contain duplicates in the destination files.
I also solved the png icons problem. By the way, the debug messages you saw are not a problem, they always appear.

First of all, thank you for taking the time to test the application.

> When adding to queue: it would be nice to see something of a counter when you add a profile to the queue.

I've been searching for this but haven't found anything similar on wxPython yet.
EDIT: I just implemented this feature too, I will make a new PR.

> Exporting the queue works but in Linux (PopOs) I have to manually add the extension. Otherwise you will not see the file when you want to import.

Ok, I just fixed it, now the extension is in preview.

> Importing a queue can only be done when you already are in the Queue Processing menu, so you first have to add something to the queue before you can open/import your earlier exported queue.

This function is already present: go to the menu bar: File -> Load queue file

> Processing
Works fine, it only shows the status of the last profile that was queued.
Would be nice when it shows all encodings like usual.

Yes, I did it specifically for this reason: the Monitoring window is used to have the current view of a series of processes, to view them all I created a special button which opens your text editor with the newly created log file .
What do you think about this, if you have a better idea I might consider it.

filelog

> Nice feature!
Probably impossible but just very nice would be parallel processing.
Well we keep that for another time.
Do not get me wrong, this little program is my BPF (Best Program Forever) ;)
That's it for now.

Thank you very much!
I think it is possible to implement parallel processing using Python's [multi-processing](https://docs.python.org/3/library/multiprocessing.html) module, but the `FFmpeg Message Monitoring` window on Videomass will have to be replaced with something else, probably just simple progress bars. However I will study this implementation, I haven't tried it yet.

Good afternoon!

**Pull request merged**
