### PR TITLE
Timeline editor accuracy

### PR DESCRIPTION
**Pull request by jeanslack**
This PR include improvements for Timeline editor: 
Added the ability to zoom up to 10 positions in order to make more accurate the time selection using slider controls.

### CODE REVIEW

**Comment by johannesdedoper** [comment]
Hello,

I checked a few new features abd they seem to be working great:
1. improvement no file required to continue: works
2. go to youtube downloader from presets/conversion: works
3. timeline zoom: nice!
4. [A/V Conversions] enable bitrate setting even with a single pass conversion by move CRF slider to -1: NICE!
Of course the ETA is great and working well.

cheers,
J

**Comment by jeanslack** [comment]
Hello, 

OK, thank you. I merged everything with the master branch, if possible use that to make sure the updates are complete.
`git clone https://github.com/jeanslack/Videomass.git -b master`

**Comment by johannesdedoper** [comment]
I tested it briefly.

I only found 1 issue.
The issue being, when I click on the "youtube downloader" on the HOME screen! it gives me an error "yt_dlp not installed ....."
However, when I go to the any other home menu (eg. presets manager etc.) and than click on "youtube downloader" it will take me there without warning. However it fails downloading as the yt_dlp is missing. This may confuse people. 

BTW: the appimages include yt_dlp I assume? 
However as yt_dlp is not offered in the POPOS! store and I can not find in the Synaptic Pack Manager, I tried downloading it through:
`sudo wget -q0 /usr/local/bin/yt-dlp https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp`
and make it executable via
`sudo chmod a+rx /usr/local/bin/yt-dlp`
Still not working in the latest master. Even after restart of Videomass. You know why?
 
Cheers, J

**Comment by jeanslack** [comment]
> I only found 1 issue.
The issue being, when I click on the "youtube downloader" on the HOME screen! it gives me an error "yt_dlp not installed ....."
However, when I go to the any other home menu (eg. presets manager etc.) and than click on "youtube downloader" it will take me there without warning. However it fails downloading as the yt_dlp is missing. This may confuse people.

This problem had already been fixed, just download the main branch [link](https://github.com/jeanslack/Videomass/archive/refs/heads/master.zip).

> BTW: the appimages include yt_dlp I assume?
However as yt_dlp is not offered in the POPOS! store and I can not find in the Synaptic Pack Manager, I tried downloading it through:
sudo wget -q0 /usr/local/bin/yt-dlp https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
and make it executable via
sudo chmod a+rx /usr/local/bin/yt-dlp
Still not working in the latest master. Even after restart of Videomass. You know why?

Yes, the Videomass AppImage also includes the yt_dlp module. However, to install yt-dlp on your OS you should open the terminal and install it like this: `python3 -m pip install --user -U yt-dlp` without using admin privileges like sudo, etc.
If pip isn't installed or you get `No module named pip` , then install it first: `sudo apt install python3-pip`

**Comment by johannesdedoper** [comment]
Ok, tried the lastest master, everything is working ;)
I also like the video to pictures converter (snapshots sort of).

Version 4.0.0 and getting better by the day!

Thnx.
J.

**Pull request closed without merging**
