### PR TITLE
External Downloader Support

### PR DESCRIPTION
**Pull request by samarthshrivas**
Added yt_dlp opts for external downloader and updated gui [incomplete].

### CODE REVIEW

**Comment by jeanslack** [comment]
Thanks again so much @samarthshrivas,

Since you have added the new options on the preferences dialog, you need to add them to the [settings_manager.py](https://github.com/samarthshrivas/Videomass/blob/master/videomass/vdms_sys/settings_manager.py) and advance a VERSION number (for example from the current 5.9 to 6.0) to make them also written in the configuration file .

But I see that you only added the controls on the preferences dialog and didn't bind them (there is no event handler yet). I think I'll do that job myself if you have no experience with wxPython.

[EDIT]
First of all, have you made sure that this implementation works on Videomass? I mean, have you even tried directly testing your new additions in `ydl_opts`?
like this:
```python
ydl_opts = {
               ...,
               ...,
                'external_downloader': '/usr/bin/aria2c', # None for default
                'external_downloader_args': '-x 2 -j 2', # List should be passed ["-j", "1", "-x", "1", "-s", "1"]
            }
```

Finally, in order to collaborate on this PR I need to be able to modify its code. Please have a look at [Allowing changes to a pull request branch created from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

See you soon.

**Comment by samarthshrivas** [comment]
> First of all, have you made sure that this implementation works on Videomass? I mean, have you even tried directly testing your new additions in ydl_opts?

Yes i tested it in seperate script. It works!. But when using external downloader progress bas in videomass does not work. (progress bas not implemented in yt-dlp for external downloader)

 Yt-dlp currently supports native, aria2c, avconv, axel, curl, ffmpeg, httpie, wget as external downloader. [Docs](https://github.com/yt-dlp/yt-dlp#download-options)

Also `Allow edits by maintainers` is checked.
image

**Comment by samarthshrivas** [comment]
Hello @jeanslack  
In [32a7689](https://github.com/jeanslack/Videomass/pull/222/commits/32a7689d23d3f2bdbbb04c0a4615592a97c281cb) almost everything is done.

Progress bar in videomass works only when downloaders is set to None (default)

**Comment by jeanslack** [comment]
Hello @samarthshrivas 

> In [32a7689](https://github.com/jeanslack/Videomass/pull/222/commits/32a7689d23d3f2bdbbb04c0a4615592a97c281cb) almost everything is done.

Excellent!

> Progress bar in videomass works only when downloaders is set to None (default)

Uhm... some might complain about this. That's okay though, I make the fixes for the linter, add a few more things for completeness, and merge it all together.

**Comment by samarthshrivas** [comment]
@jeanslack Thank you for your help and guidance with this pull request. I just wanted to let you know that this was my first time contributing to an open source project, and I really appreciate your help in making the process smooth and easy to understand. Thanks again for all your work on this project!

**Comment by jeanslack** [comment]
Closes #218

**Pull request merged**
