### PR TITLE
Add hwaccel option

### LINKED ISSUE #272: Presets with hardware acceleration
Hi, I'm trying to use Videomass with FFmpeg and make use of hardware acceleration.

So I'm trying to use the preset to input some custom parameters. But I don't know how to input the command on preset.

`ffmpeg -hwaccel qsv -c:v h264_qsv -i /root/.config/videomass/test.mp4 -c:v hevc_qsv out.mp4`

Can you give me a hand on this?

### PR DESCRIPTION
**Pull request by jeanslack**
Closes #272 

This PR includes additional arguments for Hardware Acceleration using Presets Manager.

@dev-johnny-gh please check whether this solves your issue

Other important additions have been made on AV Conversions (see changelog)

### CODE REVIEW

**Comment by dev-johnny-gh** [comment]
thanks @jeanslack , i see the Preinput_1 and 2. Can you provide me with some presets or examples with hardware acceleration? or point me to where you exactly call the FFmpeg? I'm not very familiar with the project, so it's a bit hard for me to review the whole PR.

**Comment by jeanslack** [comment]
Taking as reference the ffmpeg command line you reported in this issue #272 
`ffmpeg -hwaccel qsv -c:v h264_qsv -i /root/.config/videomass/test.mp4 -c:v hevc_qsv out.mp4`

You can apply it as shown in the example image below:

exampleHAccel

**Comment by jeanslack** [comment]
Can you test the source code of this PR and tell me if this feature meets your expectations? https://github.com/jeanslack/Videomass/archive/refs/heads/add_hwaccel_option.zip

I would need confirmation before proceeding. If you can't, that's okay too.

**Comment by dev-johnny-gh** [comment]
I use it in docker with noNVC, and then I install the image on my NAS. so I need a way to install it on Ubuntu. any idea?

actually, you can use https://github.com/jlesage/docker-baseimage-gui to build an image and push it to the docker hub, it's easier for me to test.


Dockerfile:
```
FROM jlesage/baseimage-gui:ubuntu-22.04-v4.5
LABEL maintainer="johnny <csdxf297951292@gmail.com>"

ENV APP_NAME        "videomass"
ENV APP_VERSION     "5.0.6"
ENV USER_ID         0
ENV GROUP_ID        0
ENV DISPLAY_WIDTH   "1440"
ENV DISPLAY_HEIGHT  "900"
ENV APT_SOURCE_HOST "mirrors.ustc.edu.cn"

RUN sed -i "s/archive.ubuntu.com/${APT_SOURCE_HOST}/g" /etc/apt/sources.list
RUN apt-get update -y
RUN apt install -y software-properties-common
RUN apt-add-repository ppa:jeanslack/videomass
RUN apt-get update -y
RUN apt install -y python3-videomass

COPY startapp.sh /startapp.sh
```

startapp.sh:
```
#!/bin/sh

exec /usr/bin/videomass
```

**Comment by jeanslack** [comment]
I don't know, I've never used docker, I should take the time to find out before replying to you. However, there is no problem, if you want you can try Videomass when the new release comes out.

**Comment by dev-johnny-gh** [comment]
yea, i will build the new docker image once you release a new version

**Comment by dev-johnny-gh** [comment]
> This refers to your ffmpeg command line that you reported in this issue #272 `ffmpeg -hwaccel qsv -c:v h264_qsv -i /root/.config/videomass/test.mp4 -c:v hevc_qsv out.mp4` bitmap

hi, i tested the command and it works, thanks for the great work

**Comment by jeanslack** [comment]
Thank you very much for your feedback!

**Pull request merged**
